services:
  api-gateway:
    build:
      context: ..
      dockerfile: ApiGateway/Dockerfile

    container_name: api-gateway

    ports:
      - "5000:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

    networks:
      - backend


networks:
  backend:
    external: true
    name: bookyoursport-network