include:
  - ./BookYourSport/ApiGateway/docker-compose.yml
  - ./BookYourSport/Payment/docker-compose.yml
  - ./BookYourSport/Search/docker-compose.yml
  - ./BookYourSport/Security/Auth/docker-compose.yml
  - ./BookYourSport/Services/Reservation/docker-compose.yml

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - backend

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  backend:
    external: true
    name: bookyoursport-network